server {
    listen 80;

    # Serve your frontend (SPA)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    # Proxy API routes to backend
    location /api/ {
        proxy_pass http://backend:9000/api/;
    }

}
