x-healthchecks:
  nginx: &nginx-healthcheck
    test: ["CMD", "nginx", "-t"]
    interval: 30s
    timeout: 10s
    retries: 3
  redis: &redis-healthcheck
    test: ["CMD", "redis-cli", "ping"]
    interval: 5s
    timeout: 3s
    retries: 5
  webapp: &webapp-healthcheck
    test: ["CMD", "curl", "-f", "-s", "http://localhost:8443/health"]
    interval: 10s
    timeout: 5s
    retries: 10
    start_period: 30s
    start_interval: 5s
  prometheus: &prometheus-healthcheck
    test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 15s
  vault: &vault-healthcheck
    test: ["CMD-SHELL", "curl -k -s https://localhost:8200/v1/sys/health | grep -q '\"initialized\":true' || exit 1"]
    interval: 10s
    timeout: 5s
    retries: 10
    start_period: 30s
  grafana: &grafana-healthcheck
    test: ["CMD-SHELL", "wget --no-check-certificate --no-verbose --tries=1 --spider https://localhost:3000/api/health || exit 1"]
    interval: 30s
    timeout: 10s
    retries: 5
    start_period: 30s

services:
  nginx-waf:
    image: nginx-waf
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx-waf
    ports: ["8443:443"]
    volumes:
      - logs-data:/var/log/nginx
    depends_on:
      - web-app
    healthcheck: *nginx-healthcheck
    networks: [transcendence-net]
    restart: always

  vault:
    image: vault
    container_name: vault
    build:
      context: vault
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./nginx/ssl:/vault/ssl:ro
      - ./vault/policy.hcl:/vault/policies/policy.hcl:ro
    ports: ["8444:8200"]
    networks: [transcendence-net]
    healthcheck: *vault-healthcheck
    restart: always

  redis:
    image: redis
    container_name: redis
    build:
      context: redis
      dockerfile: Dockerfile
    volumes:
      - redis-data:/data
      - logs-data:/var/log/redis
    networks: [transcendence-net]
    healthcheck: *redis-healthcheck
    restart: always

  web-app:
    image: web-app
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: web-app
    env_file: .env
    depends_on:
      vault:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./data:/app/data
      - logs-data:/app/logs
    networks: [transcendence-net]
    healthcheck: *webapp-healthcheck

  prometheus:
    image: prometheus
    build:
      context: prometheus
      dockerfile: Dockerfile
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus
      - logs-data:/logs:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks: [transcendence-net]
    healthcheck: *prometheus-healthcheck
    restart: unless-stopped

  grafana:
    image: grafana
    build:
      context: grafana
      dockerfile: Dockerfile
    container_name: grafana
    user: "root"
    env_file: .env
    volumes:
      - grafana-data:/var/lib/grafana
      - logs-data:/var/log/grafana
      - ./nginx/ssl:/etc/grafana/ssl:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports: ["8445:3000"]
    networks: [transcendence-net]
    depends_on:
      prometheus:
        condition: service_healthy
    healthcheck: *grafana-healthcheck
    restart: unless-stopped

volumes:
  redis-data:
    name: redis-data
  logs-data:
    name: logs-data
  grafana-data:
    name: grafana-data
  prometheus-data:
    name: prometheus-data

networks:
  transcendence-net:
    name: transcendence-net
    driver: bridge
    enable_ipv6: false
